apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langgraph-server
  template:
    metadata:
      labels:
        app: langgraph-server
    spec:
      containers:
      - name: langgraph-server
        image: ealen/echo-server:latest
        ports:
        - containerPort: 8003
        env:
        - name: PORT
          value: "8003"
        - name: DISABLE_LOGS
          value: "false"
        - name: ENABLE_LOGS
          value: "true"
        livenessProbe:
          httpGet:
            path: /
            port: 8003
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8003
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: langgraph-server
  namespace: default
spec:
  selector:
    app: langgraph-server
  ports:
  - port: 8003
    targetPort: 8003
  type: LoadBalancer
