# Patch: Set imagePullPolicy to Never for local images
# This allows Minikube to use images built directly in its Docker daemon

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-sdk
spec:
  template:
    spec:
      containers:
        - name: mcp-server-sdk
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
spec:
  template:
    spec:
      containers:
        - name: streamlit-ui
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-server
spec:
  template:
    spec:
      containers:
        - name: langgraph-server
          imagePullPolicy: Never
