# Automated Secrets for NeMo Data Designer
# These secrets are created from environment variables via sealed-secrets or external-secrets
# For manual setup, use: make eks-secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  # These values should be set via:
  # 1. External Secrets Operator (recommended for production)
  # 2. Sealed Secrets (for GitOps)
  # 3. Manual creation: kubectl create secret generic app-secrets --from-literal=...
  #
  # The values below are placeholders - actual secrets should NOT be committed to git
  NIM_API_KEY: "${NIM_API_KEY}"
  LLM_API_KEY: "${LITELLM_KEY}"
  LITELLM_KEY: "${LITELLM_KEY}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_REGION_NAME: "us-east-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgresql://litellm:litellm@postgres:5432/litellmdb"
  LITELLM_MASTER_KEY: "${LITELLM_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api
  namespace: default
type: Opaque
stringData:
  NGC_API_KEY: "${NGC_API_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-registry
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "nvcr.io": {
          "username": "$oauthtoken",
          "password": "${NGC_API_KEY}"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nvcrimagepullsecret
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "nvcr.io": {
          "username": "$oauthtoken",
          "password": "${NGC_API_KEY}"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nemo-db-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_PASSWORD: "nmp"
