default_agent: mock_server
agents:
  mock_server:
    name: mock_server
    entrypoint: /home/juanjbon/dev/synth-data-service/mock_mcp_server/mock_server.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /home/juanjbon/dev/synth-data-service/mock_mcp_server
    aws:
      execution_role: arn:aws:iam::668102661106:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-87646ddbeb
      execution_role_auto_create: false
      account: '668102661106'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-668102661106-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: mock_server-zqsFZ69JxH
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:668102661106:runtime/mock_server-zqsFZ69JxH
      agent_session_id: 73ad3df5-1482-4522-933d-5552a84fa93f
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: mock_server_mem-A4ohfh98Aa
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:668102661106:memory/mock_server_mem-A4ohfh98Aa
      memory_name: mock_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
