default_agent: my_mcp_server
agents:
  my_mcp_server:
    name: my_mcp_server
    entrypoint: /home/juanjbon/dev/synth-data-service/my_mcp_server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/juanjbon/dev/synth-data-service/agentcoreMcp
    aws:
      execution_role: arn:aws:iam::668102661106:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-cb7bbfb8e9
      execution_role_auto_create: false
      account: '668102661106'
      region: us-east-1
      ecr_repository: 668102661106.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-my_mcp_server
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: my_mcp_server-N3nlW04Mzc
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:668102661106:runtime/my_mcp_server-N3nlW04Mzc
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-my_mcp_server-builder
      execution_role: arn:aws:iam::668102661106:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-cb7bbfb8e9
      source_bucket: bedrock-agentcore-codebuild-sources-668102661106-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: my_mcp_server_mem-QEkoGkCDRE
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:668102661106:memory/my_mcp_server_mem-QEkoGkCDRE
      memory_name: my_mcp_server_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
