apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: litellm
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://docker.litellm.ai/berriai/litellm-helm
