# NeMo Microservices Core Stack for EKS
# This deploys the core services required for job execution

---
# NMP-Core Deployment (Jobs Controller)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmp-core
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nmp-core
  template:
    metadata:
      labels:
        app: nmp-core
    spec:
      imagePullSecrets:
      - name: ngc-registry
      containers:
      - name: nmp-core
        image: nvcr.io/nvidia/nemo-microservices/nmp-core:25.11
        args: ["--quickstart"]
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_DIALECT
          value: "postgresql"
        - name: DATABASE_USER
          value: "nmp"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nemo-db-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          value: "postgres"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "jobs"
        - name: MODELS_DATABASE_NAME
          value: "entitystore"
        - name: MODELS_DATABASE_DIALECT
          value: "postgresql"
        - name: MODELS_DATABASE_HOST
          value: "postgres"
        - name: MODELS_DATABASE_PORT
          value: "5432"
        - name: MODELS_DATABASE_USER
          value: "nmp"
        - name: MODELS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nemo-db-secrets
              key: DATABASE_PASSWORD
        - name: NIM_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NIM_API_KEY
        - name: LITELLM_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: LITELLM_KEY
        volumeMounts:
        - name: nemo-config
          mountPath: /etc/nmp
          readOnly: true
      volumes:
      - name: nemo-config
        configMap:
          name: nemo-config
---
apiVersion: v1
kind: Service
metadata:
  name: nmp-core
  namespace: default
spec:
  selector:
    app: nmp-core
  ports:
  - port: 8000
    targetPort: 8000
---
# Datastore Deployment (HuggingFace-compatible storage)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datastore
  template:
    metadata:
      labels:
        app: datastore
    spec:
      imagePullSecrets:
      - name: ngc-registry
      containers:
      - name: datastore
        image: nvcr.io/nvidia/nemo-microservices/datastore:25.11
        ports:
        - containerPort: 3000
        env:
        - name: GITEA_WORK_DIR
          value: "/nds-data/app"
        - name: APP_NAME
          value: "datastore"
        - name: DAEMON_USER
          value: "git"
        - name: DISABLE_SSH
          value: "true"
        - name: HTTP_PORT
          value: "3000"
        - name: SMTP_ENABLED
          value: "false"
        - name: GITEA__SERVER__APP_DATA_PATH
          value: "./"
        - name: GITEA__SERVER__OFFLINE_MODE
          value: "true"
        - name: GITEA__SERVER__LFS_START_SERVER
          value: "true"
        - name: GITEA__SERVER__ROOT_URL
          value: "http://localhost:3000/"
        - name: GITEA__SECURITY__INSTALL_LOCK
          value: "true"
        - name: GITEA__DATABASE__DB_TYPE
          value: "postgres"
        - name: GITEA__DATABASE__HOST
          value: "postgres:5432"
        - name: GITEA__DATABASE__NAME
          value: "datastore"
        - name: GITEA__DATABASE__USER
          value: "nmp"
        - name: GITEA__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: nemo-db-secrets
              key: DATABASE_PASSWORD
        - name: GITEA__DATABASE__SSL_MODE
          value: "disable"
        volumeMounts:
        - name: datastore-storage
          mountPath: /nds-data
      volumes:
      - name: datastore-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: datastore
  namespace: default
spec:
  selector:
    app: datastore
  ports:
  - port: 3000
    targetPort: 3000
---
# Entity Store Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-store
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: entity-store
  template:
    metadata:
      labels:
        app: entity-store
    spec:
      imagePullSecrets:
      - name: ngc-registry
      containers:
      - name: entity-store
        image: nvcr.io/nvidia/nemo-microservices/entity-store:25.11
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nemo-db-secrets
              key: DATABASE_PASSWORD
        - name: POSTGRES_USER
          value: "nmp"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "entitystore"
        - name: BASE_URL_DATASTORE
          value: "http://datastore:3000/v1/hf"
---
apiVersion: v1
kind: Service
metadata:
  name: entity-store
  namespace: default
spec:
  selector:
    app: entity-store
  ports:
  - port: 8000
    targetPort: 8000
---
# OpenBao (Vault) for secrets management
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbao
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      containers:
      - name: openbao
        image: openbao/openbao:2.3.2
        command: ["bao", "server", "-dev", "-dev-root-token-id=root"]
        ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: default
spec:
  selector:
    app: openbao
  ports:
  - port: 8200
    targetPort: 8200
